config:
  send_anonymous_usage_stats: False

grhp:
  target: dev
  outputs:
    dev:
      type: bigquery
      dataset: grhp_curated
      method: oauth
      priority: interactive
      project: thunder-1062
      threads: 1
      location: US
      job_execution_timeout_seconds: 3600
      job_retries: 1
